database: aggr.db
aggregator:
  collector:
    feeds:
    - title: feeding the monkey
      url: https://monkeyseemonkeykill.wordpress.com/
      feed: https://monkeyseemonkeykill.wordpress.com/feed/
      last_read: 1604225582
    - title: tech something
      url: http://feeds.twit.tv/twit.xml
      feed: http://feeds.twit.tv/twit.xml
      last_read: 1613329338
    - title: NOA Alerts
      url: https://alerts.weather.gov/cap/al.php?x=0
      feed: https://alerts.weather.gov/cap/al.php?x=0
      last_read: 1613639820
    - title: NASA RSS
      url: https://www.nasa.gov/content/nasa-rss-feeds
      feed: https://www.nasa.gov/rss/dyn/breaking_news.rss
      last_read: 1613572200
  renderer:
    collection:
      days: 30
    site:
      location: site/poc/
      file_name: latest.yaml
